### ISSUE TITLE
LaMetric Time OS

### ISSUE THREAD

**Issue by DrNachtschatten** [archlinuxarm/u-boot#1]
Does anyone have an entire OS image for the Lametric Time or the original partition layout for the Micro SD card?
So far there is no way to recover the LaMetric Time when the Micro SD card entirely dies (it doesn't have a backup or boot partition Flash, all is on the card).

**Comment by adadnc** [comment]
@DrNachtschatten did you find a solution or an SD Card image?

**Comment by DrNachtschatten** [comment]
@adadnc I did find a solution and got ahold of an Image.
The instructions and image are posted here: https://www.reddit.com/r/LaMetric/comments/l9xils/lametric_time_microsd_recovery_iii/
